# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'fbhackathon' do
    
platform :ios, '8.0'
use_frameworks!

pod 'Kingfisher', '~> 2.4'
pod 'Alamofire'
end

